; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:freenove_esp32_s3_wroom]
platform = espressif32 @ ^6.5.0
board = esp32-s3-devkitc-1
framework = arduino

upload_speed = 921600
monitor_speed = 115200
upload_port = /dev/cu.usbmodem5A840053251
monitor_port = /dev/cu.usbmodem5A840053251

build_flags =
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_DFU_ON_BOOT=0

lib_extra_dirs = .pio/libdeps/freenove_esp32_s3_wroom
lib_deps =
   adafruit/Adafruit NeoPixel @ ^1.12.0
   https://github.com/T-vK/ESP32-BLE-Keyboard.git
   bblanchon/ArduinoJson @ ^6.21.0

